#!/bin/bash

echo "=== DNS 변경 확인 명령어 ==="
echo ""
echo "1. nslookup 확인:"
echo "nslookup hmseok.com"
echo ""
echo "2. dig 상세 확인:"
echo "dig hmseok.com"
echo ""
echo "3. ping 테스트:"
echo "ping hmseok.com"
echo ""
echo "4. curl 테스트:"
echo "curl -I http://hmseok.com"
echo "curl -I https://hmseok.com"
echo ""
echo "5. API 테스트:"
echo "curl http://hmseok.com/api/cars"
echo ""
echo "=== 예상 결과 ==="
echo "IP 주소가 43.201.22.156으로 변경되어야 합니다."
echo "TTL 값이 낮아지면서 빠르게 변경됩니다." 